README.md
Fixing errors found in Readme documentation.
=> Fixing typos in ReadMe

.gitignore, gradle/wrapper/gradle-wrapper.properties, tests/build.gradle, tests/src/test/scala/runtime/actionContainers/ActionLoopContainerTests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopGoContainerTests.scala, tests/src/test/scala/runtime/actionContainers/GoResourceHelpers.scala, tools/travis/build.sh, tools/travis/setup.sh, tools/travis/test.sh
=> Unit tests

examples/bash-hello/Makefile, examples/golang-hello-single/Makefile, examples/golang-hello-vendor/Makefile, examples/golang-hello-vendor/src/hello/Gopkg.lock, examples/golang-main-package/Makefile, examples/golang-main-single/Makefile, examples/golang-main-standalone/Makefile, examples/golang-main-vendor/Makefile, examples/golang-main-vendor/src/main/Gopkg.lock
this fixes a problem with the GOPATH in the makefile examples
=> use compiler image for golang-main-package devel target

openwhisk/compiler.go, openwhisk/executor.go, openwhisk/executor_test.go, openwhisk/extractor.go, openwhisk/initHandler_test.go, openwhisk/runHandler.go, openwhisk/util_test.go
also cleaned tests and pinned the h2non dependency
=> fixed unsynced log bugs

.travis.yml, build.gradle, golang1.11/Dockerfile
=> Bump go to 1.11.3

golang1.11/CHANGELOG.md, golang1.11/Dockerfile
=> bump Go to 1.11.4

.travis.yml, build.gradle, golang1.11/CHANGELOG.md, golang1.11/Dockerfile
Update to go v1.11.6 (security updates).
=> Update to go v1.11.6 (security updates).

.travis.yml
reverting another wrong change...
=> reverting again

.travis.yml, CHANGES.md, actionloop/build.gradle, docs/BUILD.md, golang1.11/Dockerfile, golang1.11/build.gradle, golang1.12/Dockerfile, golang1.12/build.gradle, tools/travis/setup.sh
=> go upgrade

common/gobuild.py.launcher.go, examples/Makefile, examples/bash-hello/Makefile, examples/benchmark/Makefile, examples/golang-hello-single/Makefile, examples/golang-hello-vendor/Makefile, examples/golang-main-package/Makefile, examples/golang-main-single/Makefile, examples/golang-main-standalone/Makefile, examples/golang-main-vendor/Makefile, openwhisk/_test/env.sh, openwhisk/actionProxy.go, openwhisk/actionProxy_test.go, openwhisk/executor.go, openwhisk/executor_test.go, openwhisk/initHandler.go, openwhisk/initHandler_test.go, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGo12Tests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGoTests.scala
Supporting env at init, propagated to the executable.
=> env support

docs/DEPLOY.md
Fixed tpyo in link to VSCode and added syntax highlighter to golang code
=> Fixed tpyo in link to VSCode and added syntax highlighter to golang code

tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGo12Tests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGoTests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicTests.scala
See https://github.com/apache/openwhisk/pull/4761.
=> Update for action version.

golang1.15/Dockerfile
This PR gathers the latest security fixes for GO 1.15
=> Gather fixes for Go 1.15

settings.gradle, tests/build.gradle
See https://github.com/apache/openwhisk/issues/5132. Some of these may be removed when upstream changes are merged.
=> Resolve akka versions explicitly.

.travis.yml, CHANGES.md, golang1.15/Dockerfile
Update to Go 1.15.14 to gather TLS related fixes
=> Update go 1.15 to go 1.15.14 to gather fixes

examples/Makefile, examples/aws-main/Makefile, examples/aws-main/go.mod, examples/aws-main/go.sum, examples/aws-main/main.go, examples/bash/Makefile, examples/package-main/Makefile, examples/single-hello/Makefile, examples/single-main/Makefile, examples/standalone/Makefile
Updates examples to run against 1.16
Added a new example to invoke the AWS API to test complex modules building.
=> New example aws

.travis.yml, CHANGES.md, golang1.18/Dockerfile, golang1.18/Makefile, golang1.18/bin/compile, golang1.18/build.gradle, golang1.18/lib/launcher.go, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGo18Tests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopGo18ContainerTests.scala
Pull request will require a new release
=> Add golang:1.18

docs/ACTION.md
Forgot add document for previous pr: https://github.com/apache/openwhisk-runtime-go/pull/170
So add document in this pr.
=> Add document for support array result

.travis.yml, CHANGES.md, golang1.19/Dockerfile, golang1.19/Makefile, golang1.19/bin/compile, golang1.19/build.gradle, golang1.19/lib/launcher.go, tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGo19Tests.scala, tests/src/test/scala/runtime/actionContainers/ActionLoopGo19ContainerTests.scala
Add latest runtime fo go (1.19)
=> Add golang 1.19 Runtime

docs/ACTION.md
=> missed doc update for array results
