apache/openwhisk-runtime-go

.travis.yml
build.gradle
golang1.11/Dockerfile

This allows:
- more stable upgrades/bumps
- In CICD pipelines where there is a different version of go installed, the gradle config will use the correct one when running the tests

ping go version

---

.travis.yml
build.gradle
golang1.11/CHANGELOG.md

go1.11.5 (released 2019/01/23) includes a security fix to the crypto/elliptic package. See the [Go 1.11.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.11.5+label%3ACherryPickApproved) on our issue tracker for details.

update go from 1.11.4 to 1.11.5

---

golang1.11/Dockerfile

The main library for using Kafka in go is confluentinc/confluent-go-kafka
Unfortuanately it is based on the C library librdkafka
This patch installs librdkafka in the Go image to support it

add support for confluent-go-kafka library

---

.travis.yml
actionloop/build.gradle

Since everything else fails, now the build for the docker containers for actionloop builds with the go command the static executables with a dirty "go build" call instead of relying on the badly broken go Gradle plugin that insists building a dynamic one in Travis even if it works correctly on OSX.
Will it work? Will I ever be able to use actionloop with Alpine based images that does not have the glibc in it?

Will our heroes be able to build a static go executable with travis?

---

.gitignore
CHANGES.md
build.gradle
common/gobuild.py
go.mod
go.sum
golang1.11/build.gradle
golang1.12/Dockerfile
golang1.12/build.gradle
openwhisk/_test/build.sh
openwhisk/_test/jar/META-INF/MANIFEST.MF
openwhisk/_test/jar/hello.txt
openwhisk/compiler.go
openwhisk/extractor.go
openwhisk/extractor_test.go
openwhisk/filetype.go
openwhisk/initHandler.go
openwhisk/runHandler.go
openwhisk/util_test.go
openwhisk/version.go
openwhisk/zip.go
openwhisk/zip_test.go
settings.gradle
tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGo12Tests.scala
tests/src/test/scala/runtime/actionContainers/ActionLoopGo12ContainerTests.scala
tests/src/test/scala/runtime/actionContainers/ActionLoopGoContainerTests.scala
tools/travis/build.sh
tools/travis/setup.sh
tools/travis/test.sh

- Support for Go 1.12.4
- Support for jar not expanded for Java when set OW_SAVE_JAR
- You can initalize multiple times when debugging
- Removed gogradle plugin, now building directly with go

Go12 jar support

---

openwhisk/actionProxy.go

See https://github.com/apache/openwhisk/pull/4765 for some background. The tests in this repo fail when the test is fixed.
With this patch, now the tests pass.

Export API host from parent process to child process.

---

openwhisk/actionProxy.go

This change allows to propagate any variable starting with `__OW_` to the underlying process (not just __OW_API_HOST). This fix is in conjunction to the ability to set variables in the standalone openwhisk to provide the informations to start an action under a debugger. This feature is going to be implemented first in the upcoming typescript runtime.

propagate openwhisk vars to the underlying process

---

examples/golang-hello-vendor/src/hello/Gopkg.toml
examples/golang-main-vendor/src/main/Gopkg.toml

we added .toml to scancode config as part of runtime-rust release; now
we need to add the license headers to the .toml files here.

add license headers to .toml files

---

CHANGES.md
golang1.11/CHANGELOG.md
golang1.11/Dockerfile
golang1.12/CHANGELOG.md

- Updated golang1.12 to go 1.12.17.
- Add 'apt-get upgrade' to the image builds to include security fixes with each build in case the used base image is not updated frequently.
In case the base image is updated frequently the 'apt-get upgrade' is a no operation. If not it will catch the security updates available since the last update of the base image.
This change was not done for the actionloop/Dockerfile as this directly points to the ubuntu base image (ubuntu:xenial) which contains the security fixes.

Update to go 1.12.17, include secuity fixes with every build.

---

.travis.yml
common/gobuild.py

Seems github.com/stretchr/testify/assert is not compatible with go 1.12

Upgrade golang version to 1.13 in travis

---

openwhisk/zip.go

I'm trying to switch runtime user to non-root one, but some tests are failed because of permission error(sub dir may be created with `0644`), I think `0755` is a reasonable mode for all sub dirs regardless of what permission mode they really have

Make unzip always create sub dir with mode 0755

---

CHANGES.md
golang1.13/Dockerfile
golang1.15/Dockerfile

- go 1.15 runtime upgraded to 1.15.5
- go 1.13 runtime upgraded to 1.13.15
- add 'apt-get upgrade' to the image build of go 1.15 and go 1.13 to get latest security fixes during each build, for the case the base images are not updated frequently

Fetch security fixes in build. Upgrade go versions.

---

.travis.yml

Changes Travis to use Go 1.15.13 to be on a supported version

Build in Travis with go 1.15.13 which is a supported version

---

.gitignore
CHANGES.md
openwhisk/_test/build.sh
openwhisk/util_test.go
openwhisk/version.go
openwhisk/zip.go
openwhisk/zip_test.go

This patch implements the ability to zip and unzip symlinks, essential feature to use virtualenvs like those in Python.

Symlink in zips

---

CHANGES.md
main/proxy.go

- Extend `proxy -version` to also show the go version the proxy.go was compiled with (makes it easier to check if go security updates need to be applied).

Extend `proxy -version` to also show the go runtime version.

---

.travis.yml
golang1.15/Dockerfile
golang1.16/Dockerfile

- Relax the builds of the go1.15 and go1.16 runtimes to automatically use the latest go patch level instead of using fixed ones.
This allows to automatically include the latest security fixes for these runtimes. Up to now this always required a change and therefore a PR to be processed.
Relaxing this allows these runtimes to automatically stay actual without further effort.
This is basically the same behavior as used for example for the python:3.7 (https://github.com/apache/openwhisk-runtime-python/blob/16c608107beee74078eaf47c82a1db4e24602b38/core/python3Action/Dockerfile#L19) or the swift:5.3 (https://github.com/apache/openwhisk-runtime-swift/blob/60fb30cbd17f967736b4309d17f706ff26279e2f/core/swift53Action/Dockerfile#L19) runtimes.
- For the go 1.16 image it was necessary to use …

Automatically include go1.15.x and go1.16.x security fixes during build.

---

golang1.17/bin/compile

The compile script for golang 1.17 actions will now work with python 3 as well as continue to work with Python 2

Python 2 and 3 support for go 1.17 runtime

---

golang1.15/Dockerfile
golang1.16/Dockerfile
golang1.17/Dockerfile

This is for convenience so customers can package their actions inside of the runtime.

Install zip

---

build.gradle
golang1.17/Dockerfile
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
openwhisk/runHandler.go
tests/build.gradle

Upgrade gradle version

---

common/gobuild.py.launcher.go
golang1.17/lib/launcher.go
golang1.18/lib/launcher.go
openwhisk/runHandler.go
tests/src/test/scala/runtime/actionContainers/ActionLoopGoContainerTests.scala

Support array result include sequence action

---

.travis.yml
openwhisk/_test/pysample/lib/exec.py

Current travis build VM is still using xenial (16.04) as base. Updates to this image caused build breaks. 
Updating to a more recent build environment (same as for apache/openwhisk -> https://github.com/apache/openwhisk/blob/master/.travis.yml) should reduce these from happening.
Also need to update to a current go version on the build environment as only go 1.18 and go 1.19 are actually supported.

Update to recent travis build vm to unblock build.

---

golang1.19/Dockerfile

code can be removed when the base image updates standard library 
```bash
#Update net Package as temporary vulnerability fix
cd /usr/local/go/src/ &&\
go get -u golang.org/x/net@v0.8.0 &&\
```

Update net Package as temporary vulnerability fix

---

CHANGES.md
golang1.20/Dockerfile
golang1.21/Dockerfile
golang1.22/Dockerfile

The support for the buster-backports repository is now dropped by debian. Options are 
- to jump to a newer backports repository
- or to remove this dependency as it seems it is currently not used.
For now we will remove this dependency (reduce complexity).

Remove dependency on obsolete buster-backports respository.
